### ISSUE TITLE
"getObservable" only exists in the README and not in the actual codebase

### ISSUE THREAD

**Issue by null4bl3** [uniprank/ngx-scrollspy#28]
i get that this was portet from the [JonnyBGod](https://github.com/jonnybgod/ngx-scrollspy) repository, but removed the most basic function, and still mentioning it in the documentation is just not good practice.

There now seems to be a "observe" function, but that is unable to locate any ids.

Could someone please update the README to reflect the actual usage of this NPM module ?

**Comment by Denfie** [comment]
The reason why it is maybe not included more is that I changed the code base and forgot to change the Readme as well. But yes I was a little bit inspired by different kinds of repositories. For our client is this solution this one which is really needed. Just compare both repositories to see that this one is different.

For a working example take a look at the example page: https://uniprank.github.io/ngx-scrollspy/test-case-1
The documentation there is more up-to-date. But thanks I will change the readme as well.

**Comment by Denfie** [comment]
I think README is now up-to-date so I will close this issue. Thanks for your report.
